const DEFAULT_CATEGORY_ICON = 'Language'
const DEFAULT_CATEGORY_ICON_COLOR = '#66C42C'
const DEFAULT_CATEGORY_LIMIT = 20
const DEFAULT_CATEGORY_SKIP = 0

module.exports = {
  DEFAULT_CATEGORY_ICON,
  DEFAULT_CATEGORY_ICON_COLOR,
  DEFAULT_CATEGORY_LIMIT,
  DEFAULT_CATEGORY_SKIP
}
